In [2]:
#pip install tensorflow
#pip install keras
#pip install gensim
import pandas as pd
import numpy as np
#conda install numpy

In [3]:

df1 = pd.read_csv('C:\\Users\\USER\\Documents\\random_positive.csv')
df1.head(5)

review     label
0  literally right next train station hongdae off...  Positive
1                               get top climb metres  Positive
2  best place get amazing view city well worth wa...  Positive
3  opens late offers amazing view city mapped end...  Positive
4  energy love going market place truly massive e...  Positive

In [4]:
df2=pd.read_csv('C:\\Users\\USER\\Documents\\random_negative.csv')
df2.head(5)

review     label
0  book eiffel tower anything special boyfriend g...  Negative
1  beautiful architecture way many people hot plu...  Negative
2  main official residence thai royal family larg...  Negative
3  scope size art louvre amazing however tourists...  Negative
4  waited queue hour get tickets another mins go ...  Negative

In [5]:
df3=pd.concat([df1,df2])
df3.shape

(10000, 2)

In [6]:
# 한번만 시행하고 재시행하지 말것

df3['nlabel']=np.where(df3['label']=='Positive',1,0)
df=df3.drop(['label'], axis=1)
df.head()

review  nlabel
0  literally right next train station hongdae off...       1
1                               get top climb metres       1
2  best place get amazing view city well worth wa...       1
3  opens late offers amazing view city mapped end...       1
4  energy love going market place truly massive e...       1

In [7]:
from keras.preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts(df['review'])
vocab_size = len(t.word_index) + 1

X_encoded = t.texts_to_sequences(df['review'])
max_length=max(len(l) for l in X_encoded)

from keras.preprocessing.sequence import pad_sequences
X_train=pad_sequences(X_encoded, maxlen=max_length, padding='post')
print(X_train)

Using TensorFlow backend.


[[ 557  208  247 ...    0    0    0]
 [   4   53  751 ...    0    0    0]
 [  72    1    4 ...    0    0    0]
 ...
 [  54   54   54 ...    0    0    0]
 [  82 1665  232 ...    0    0    0]
 [  13    1  135 ...    0    0    0]]


In [8]:
import numpy as np
embedding_dict = dict()
f = open('C:\\Users\\USER\\Documents\\GH\\내부플젝\\glove.6B\\glove.6B.100d.txt', encoding="utf8")

for line in f:
    word_vector = line.split()
    word = word_vector[0]
    word_vector_arr = np.asarray(word_vector[1:], dtype='float32') # 100개의 값을 가지는 array로 변환
    embedding_dict[word] = word_vector_arr
f.close()
print('%s개의 Embedding vector가 있습니다.' % len(embedding_dict))


400000개의 Embedding vector가 있습니다.


In [43]:
print(embedding_dict['respectable'])
print(len(embedding_dict['respectable']))

[-0.049773   0.19903    0.10585    0.1391    -0.32395    0.44053
  0.3947    -0.22805   -0.25793    0.49768    0.15384   -0.08831
  0.0782    -0.8299    -0.037788   0.16772   -0.45197   -0.17085
  0.74756    0.98256    0.81872    0.28507    0.16178   -0.48626
 -0.006265  -0.92469   -0.30625   -0.067318  -0.046762  -0.76291
 -0.0025264 -0.018795   0.12882   -0.52457    0.3586     0.43119
 -0.89477   -0.057421  -0.53724    0.25587    0.55195    0.44698
 -0.24252    0.29946    0.25776   -0.8717     0.68426   -0.05688
 -0.1848    -0.59352   -0.11227   -0.57692   -0.013593   0.18488
 -0.32507   -0.90171    0.17672    0.075601   0.54896   -0.21488
 -0.54018   -0.45882   -0.79536    0.26331    0.18879   -0.16363
  0.3975     0.1099     0.1164    -0.083499   0.50159    0.35802
  0.25677    0.088546   0.42108    0.28674   -0.71285   -0.82915
  0.15297   -0.82712    0.022112   1.067     -0.31776    0.1211
 -0.069755  -0.61327    0.27308   -0.42638   -0.085084  -0.17694
 -0.0090944  0.1109     0.

In [9]:
embedding_matrix = np.zeros((vocab_size, 100))
# 단어 집합 크기의 행과 100개의 열을 가지는 행렬 생성. 값은 전부 0으로 채워진다.
np.shape(embedding_matrix) 

(14677, 100)

In [45]:
print(t.word_index.items()) #보면은 markets market 도의어로 처리 안되어있음

dict_items([('market', 1), ('food', 2), ('place', 3), ('street', 4), ('namdaemun', 5), ('good', 6), ('korean', 7), ('get', 8), ('find', 9), ('clothes', 10), ('souvenirs', 11), ('shopping', 12), ('buy', 13), ('many', 14), ('one', 15), ('shops', 16), ('great', 17), ('seoul', 18), ('stalls', 19), ('cheap', 20), ('visit', 21), ('go', 22), ('also', 23), ('around', 24), ('price', 25), ('like', 26), ('lots', 27), ('prices', 28), ('shop', 29), ('time', 30), ('korea', 31), ('items', 32), ('clothing', 33), ('much', 34), ('local', 35), ('see', 36), ('try', 37), ('selling', 38), ('walk', 39), ('everything', 40), ('bargain', 41), ('experience', 42), ('people', 43), ('lot', 44), ('things', 45), ('area', 46), ('etc', 47), ('stuff', 48), ('shoes', 49), ('really', 50), ('traditional', 51), ('goods', 52), ('vendors', 53), ('went', 54), ('want', 55), ('looking', 56), ('found', 57), ('accessories', 58), ('markets', 59), ('better', 60), ('myeongdong', 61), ('day', 62), ('cheaper', 63), ('best', 64), ('nice

In [10]:
for word, i in t.word_index.items(): # 훈련 데이터의 단어 집합에서 단어를 1개씩 꺼내온다.
    temp = embedding_dict.get(word) # 단어(key) 해당되는 임베딩 벡터의 100개의 값(value)를 임시 변수에 저장
    if temp is not None:
        embedding_matrix[i] = temp # 임수 변수의 값을 단어와 맵핑되는 인덱스의 행에 삽입

In [11]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten

model = Sequential()
embedding_layer = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_length, trainable=False)

In [12]:
max_words=max_length

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
import re

In [14]:

max_fatures = 30000
tokenizer = Tokenizer(nb_words=max_fatures, split=' ')
tokenizer.fit_on_texts(df['review'].values)
X1 = tokenizer.texts_to_sequences(df['review'].values)
X1 = pad_sequences(X1)
Y1 = pd.get_dummies(df['nlabel']).values
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1,Y1, random_state = 42)
print(X1_train.shape,Y1_train.shape)
print(X1_test.shape,Y1_test.shape)

C:\Users\USER\Anaconda3\lib\site-packages\keras_preprocessing\text.py:178: UserWarning: The `nb_words` argument in `Tokenizer` has been renamed `num_words`.
  warnings.warn('The `nb_words` argument in `Tokenizer` '


(7500, 251) (7500, 2)
(2500, 251) (2500, 2)


In [71]:
embed_dim = 100
lstm_out = 200
model = Sequential()
model.add(embedding_layer)
model.add(LSTM(128, dropout=0.5, return_sequences=False
               , input_shape=(max_length,embed_dim)))
model.add(Dense(2,activation='softmax')) #예측하고자 하는 수에 따라 숫자
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 251, 100)          1467700   
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               117248    
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 258       
Total params: 1,585,206
Trainable params: 117,506
Non-trainable params: 1,467,700
_________________________________________________________________
None


In [72]:
batch_size = 32
model.fit(X1_train, Y1_train, nb_epoch = 3, batch_size=batch_size, verbose = 2)

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/3
 - 84s - loss: 0.4447 - acc: 0.7913
Epoch 2/3
 - 76s - loss: 0.3028 - acc: 0.8716
Epoch 3/3
 - 76s - loss: 0.2340 - acc: 0.9015


In [73]:
score,acc = model.evaluate(X1_test, Y1_test, verbose = 2, batch_size = batch_size)
print("score: %.2f" % (score))
print("acc: %.2f" % (acc))

score: 0.13
acc: 0.95


In [74]:
pos_cnt, neg_cnt, pos_correct, neg_correct = 0, 0, 0, 0
for x in range(len(X1_test)):
    
    result = model.predict(X1_test[x].reshape(1,X1_test.shape[1]),batch_size=1,verbose = 2)[0]
   
    if np.argmax(result) == np.argmax(Y1_test[x]):
        if np.argmax(Y1_test[x]) == 0:
            neg_correct += 1
        else:
            pos_correct += 1
       
    if np.argmax(Y1_test[x]) == 0:
        neg_cnt += 1
    else:
        pos_cnt += 1



print("pos_acc", pos_correct/pos_cnt*100, "%")
print("neg_acc", neg_correct/neg_cnt*100, "%")

pos_acc 95.51886792452831 %
neg_acc 94.70684039087948 %


In [24]:
df4= pd.read_csv("C:\\Users\\USER\\Documents\\GH\\내부플젝\\data_vader_labelled_without stemLem\\cheong_label.csv")
df4.head()

review  rating    neg    pos  \
0  came evening scenery quite beautiful wind blow...       5  0.000  0.453   
1  people like strolling around stream especially...       5  0.092  0.321   
2  long stream stretch km along stream find nicel...       5  0.000  0.482   
3  first night everything decorated lanterns budd...       5  0.000  0.339   
4  great illustration talent commitment korean pe...       4  0.000  0.533   

     neu  compound     label  
0  0.547    0.9336  Positive  
1  0.587    0.4432  Positive  
2  0.518    0.9485  Positive  
3  0.661    0.8016  Positive  
4  0.467    0.9432  Positive

In [20]:
df5= pd.read_csv("C:\\Users\\USER\\Documents\\GH\\내부플젝\\data_vader_labelled_without stemLem\\gung_label.csv")
df5.head()

review  rating    neg    pos  \
0  best way see place rent korean costume able ta...       5  0.000  0.480   
1  good palace overall may went first time lots p...       4  0.000  0.244   
2  gate impressive grounds well entrance fee inte...       4  0.000  0.349   
3  visited place around pm changing guard pm amaz...       5  0.000  0.262   
4  timing critical want see changing guard tour g...       5  0.052  0.325   

     neu  compound     label  
0  0.520    0.8519  Positive  
1  0.756    0.9313  Positive  
2  0.651    0.9260  Positive  
3  0.738    0.7506  Positive  
4  0.623    0.9617  Positive

In [53]:
df6= pd.read_csv("C:\\Users\\USER\\Documents\\GH\\내부플젝\\data_vader_labelled_without stemLem\\insadong_label.csv")
df6.head()

review  rating  neg    pos  \
0  well know places usually things prices varying...       5  0.0  0.164   
1  looking place buy local souvenirs bunch local ...       4  0.0  0.000   
2  shop many traditional korean arts crafts nice ...       4  0.0  0.203   
3  main ntique street little tourist mall side st...       3  0.0  0.119   
4  bit atypical shopping area mix art galleries i...       4  0.0  0.197   

     neu  compound     label  
0  0.836    0.7703  Positive  
1  1.000    0.0000   Neutral  
2  0.797    0.4215  Positive  
3  0.881    0.4019  Positive  
4  0.803    0.4019  Positive

In [92]:
df7= pd.read_csv("C:\\Users\\USER\\Documents\\GH\\내부플젝\\data_vader_labelled_without stemLem\\chon_label.csv")
df7.head()

review  rating    neg    pos  \
0  great look feel stepped back century novelty b...     4.0  0.000  0.301   
1  bad lot see fairly packed tourists even rainy ...     2.0  0.298  0.205   
2  houses look great nice walk around absolutely ...     3.0  0.000  0.496   
3  people housing area resident time business ren...     3.0  0.000  0.145   
4  bukchon hanok village situated middle modern p...     3.0  0.000  0.272   

     neu  compound     label  
0  0.699    0.8481  Positive  
1  0.497   -0.1280  Negative  
2  0.504    0.7845  Positive  
3  0.855    0.5994  Positive  
4  0.728    0.7964  Positive

In [131]:
df4['lstm_label']=np.zeros(len(df4))
df4.review=df4.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
twt8 = tokenizer.texts_to_sequences(df4['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
twt8 = pad_sequences(twt8, maxlen=max_length, dtype='int32', value=0)
print(twt8)

[[    0     0     0 ...   571  3093   161]
 [    0     0     0 ...   212  5054 13285]
 [    0     0     0 ...    22   796     6]
 ...
 [    0     0     0 ...  4885    10   122]
 [    0     0     0 ...     5   129    25]
 [    0     0     0 ...    27    55   385]]


In [132]:
criteria = [df4['rating'].between(1, 2), df4['rating'].between(3, 5)]
values = [0, 1]

df4['rrating'] = np.select(criteria, values, 0)
df4.head()

review  rating    neg    pos  \
0  came evening scenery quite beautiful wind blow...       5  0.000  0.453   
1  people like strolling around stream especially...       5  0.092  0.321   
2  long stream stretch km along stream find nicel...       5  0.000  0.482   
3  first night everything decorated lanterns budd...       5  0.000  0.339   
4  great illustration talent commitment korean pe...       4  0.000  0.533   

     neu  compound     label  lstm_label  relstm_label  rrating  
0  0.547    0.9336  Positive         0.0           0.0        1  
1  0.587    0.4432  Positive         0.0           0.0        1  
2  0.518    0.9485  Positive         0.0           0.0        1  
3  0.661    0.8016  Positive         0.0           0.0        1  
4  0.467    0.9432  Positive         0.0           0.0        1

In [133]:
sentiment= model.predict(twt8,batch_size=32,verbose = 2)
for i in range(len(twt8)):
    df4.iloc[i,7]=np.argmax(sentiment[i])

In [134]:
df4['lstm_label']=np.where(df4.lstm_label==1.0,1,0)
df4['nlstm_label']=np.where(df4.label=='Positive',1,0)
df4.head()


review  rating    neg    pos  \
0  came evening scenery quite beautiful wind blow...       5  0.000  0.453   
1  people like strolling around stream especially...       5  0.092  0.321   
2  long stream stretch km along stream find nicel...       5  0.000  0.482   
3  first night everything decorated lanterns budd...       5  0.000  0.339   
4  great illustration talent commitment korean pe...       4  0.000  0.533   

     neu  compound     label  lstm_label  relstm_label  rrating  nlstm_label  
0  0.547    0.9336  Positive           1           0.0        1            1  
1  0.587    0.4432  Positive           0           0.0        1            1  
2  0.518    0.9485  Positive           0           0.0        1            1  
3  0.661    0.8016  Positive           1           0.0        1            1  
4  0.467    0.9432  Positive           1           0.0        1            1

In [135]:
np.mean(df4.lstm_label == df4.rrating)

0.7291208791208791

In [136]:
np.mean(df4.lstm_label==df4.nlstm_label)

0.7483516483516484

In [141]:
df5['lstm_label']=np.zeros(len(df5))
df5.review=df5.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
twt2 = tokenizer.texts_to_sequences(df5['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
twt2 = pad_sequences(twt2, maxlen=max_length, dtype='int32', value=0)
print(twt2)

[[   0    0    0 ...   31   20  192]
 [   0    0    0 ...   18 1048   94]
 [   0    0    0 ...  427    2  582]
 ...
 [   0    0    0 ...  775    1 3941]
 [   0    0    0 ...  718  928  420]
 [   0    0    0 ...   82   31  277]]


In [142]:
criteria = [df5['rating'].between(1, 2), df5['rating'].between(3, 5)]
values = [0, 1]

df5['rrating'] = np.select(criteria, values, 0)
df5.head()

review  rating    neg    pos  \
0  best way see place rent korean costume able ta...       5  0.000  0.480   
1  good palace overall may went first time lots p...       4  0.000  0.244   
2  gate impressive grounds well entrance fee inte...       4  0.000  0.349   
3  visited place around pm changing guard pm amaz...       5  0.000  0.262   
4  timing critical want see changing guard tour g...       5  0.052  0.325   

     neu  compound     label  lstm_label  rrating  nlstm_label  
0  0.520    0.8519  Positive         0.0        1            1  
1  0.756    0.9313  Positive         0.0        1            1  
2  0.651    0.9260  Positive         0.0        1            1  
3  0.738    0.7506  Positive         0.0        1            1  
4  0.623    0.9617  Positive         0.0        1            1

In [143]:
sentiment= model.predict(twt2,batch_size=32,verbose = 2)
for i in range(len(twt2)):
    df5.iloc[i,7]=np.argmax(sentiment[i])

In [144]:
df5['lstm_label']=np.where(df5.lstm_label==1.0,1,0)
df5['nlstm_label']=np.where(df5.label=='Positive',1,0)
df5.head()


review  rating    neg    pos  \
0  best way see place rent korean costume able ta...       5  0.000  0.480   
1  good palace overall may went first time lots p...       4  0.000  0.244   
2  gate impressive grounds well entrance fee inte...       4  0.000  0.349   
3  visited place around pm changing guard pm amaz...       5  0.000  0.262   
4  timing critical want see changing guard tour g...       5  0.052  0.325   

     neu  compound     label  lstm_label  rrating  nlstm_label  
0  0.520    0.8519  Positive           1        1            1  
1  0.756    0.9313  Positive           1        1            1  
2  0.651    0.9260  Positive           0        1            1  
3  0.738    0.7506  Positive           1        1            1  
4  0.623    0.9617  Positive           0        1            1

In [145]:
np.mean(df5.lstm_label == df5.rrating)

0.5552941176470588

In [146]:
np.mean(df5.lstm_label == df5.nlstm_label)

0.5690196078431372

In [108]:
df6['lstm_label']=np.zeros(len(df6))
df6.review=df6.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
twt3 = tokenizer.texts_to_sequences(df6['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
twt3 = pad_sequences(twt3, maxlen=max_length, dtype='int32', value=0)
print(twt3)

[[   0    0    0 ...  397   63  357]
 [   0    0    0 ...  393  672   34]
 [   0    0    0 ...  494  420  121]
 ...
 [   0    0    0 ...   44   11  121]
 [   0    0    0 ...  183  247   11]
 [   0    0    0 ... 4272   11 1507]]


In [114]:
criteria = [df6['rating'].between(1, 2), df6['rating'].between(3, 5)]
values = [0, 1]

df6['rrating'] = np.select(criteria, values, 0)
df6.head()

review  rating  neg    pos  \
0  well know places usually things prices varying...       5  0.0  0.164   
1  looking place buy local souvenirs bunch local ...       4  0.0  0.000   
2  shop many traditional korean arts crafts nice ...       4  0.0  0.203   
3  main ntique street little tourist mall side st...       3  0.0  0.119   
4  bit atypical shopping area mix art galleries i...       4  0.0  0.197   

     neu  compound     label  lstm_label  rrating  
0  0.836    0.7703  Positive         1.0        1  
1  1.000    0.0000   Neutral         1.0        1  
2  0.797    0.4215  Positive         1.0        1  
3  0.881    0.4019  Positive         1.0        1  
4  0.803    0.4019  Positive         1.0        1

In [112]:
sentiment= model.predict(twt3,batch_size=32,verbose = 2)
for i in range(len(twt3)):
    df6.iloc[i,7]=np.argmax(sentiment[i])

In [115]:
df6['lstm_label']=np.where(df6.lstm_label==1.0,1,0)
df6['nlstm_label']=np.where(df6.label=='Positive',1,0)
df6.head()

review  rating  neg    pos  \
0  well know places usually things prices varying...       5  0.0  0.164   
1  looking place buy local souvenirs bunch local ...       4  0.0  0.000   
2  shop many traditional korean arts crafts nice ...       4  0.0  0.203   
3  main ntique street little tourist mall side st...       3  0.0  0.119   
4  bit atypical shopping area mix art galleries i...       4  0.0  0.197   

     neu  compound     label  lstm_label  rrating  nlstm_label  
0  0.836    0.7703  Positive           1        1            1  
1  1.000    0.0000   Neutral           1        1            0  
2  0.797    0.4215  Positive           1        1            1  
3  0.881    0.4019  Positive           1        1            1  
4  0.803    0.4019  Positive           1        1            1

In [118]:
np.mean(df6.lstm_label == df6.nlstm_label)

0.8641025641025641

In [119]:
np.mean(df6.lstm_label == df6.rrating)

0.9452991452991453

In [93]:
df7['lstm_label']=np.zeros(len(df7))
df7.review=df7.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
twt4 = tokenizer.texts_to_sequences(df7['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
twt4 = pad_sequences(twt4, maxlen=max_length, dtype='int32', value=0)
print(twt4)

[[   0    0    0 ...   20  238 1948]
 [   0    0    0 ...   26  568 1032]
 [   0    0    0 ...  352  229   47]
 ...
 [   0    0    0 ...  452  489   19]
 [   0    0    0 ...   26  199 4792]
 [   0    0    0 ...    0    0    0]]


In [97]:
criteria = [df7['rating'].between(1, 2), df7['rating'].between(3, 5)]
values = [0, 1]

df7['rrating'] = np.select(criteria, values, 0)
df7.head()

review  rating    neg    pos  \
0  great look feel stepped back century novelty b...     4.0  0.000  0.301   
1  bad lot see fairly packed tourists even rainy ...     2.0  0.298  0.205   
2  houses look great nice walk around absolutely ...     3.0  0.000  0.496   
3  people housing area resident time business ren...     3.0  0.000  0.145   
4  bukchon hanok village situated middle modern p...     3.0  0.000  0.272   

     neu  compound     label  lstm_label  rrating  
0  0.699    0.8481  Positive         1.0        1  
1  0.497   -0.1280  Negative         0.0        0  
2  0.504    0.7845  Positive         1.0        1  
3  0.855    0.5994  Positive         1.0        1  
4  0.728    0.7964  Positive         1.0        1

In [94]:
sentiment= model.predict(twt4,batch_size=32,verbose = 2)

In [95]:
for i in range(len(twt4)):
    df7.iloc[i,7]=np.argmax(sentiment[i])
df7.head()


review  rating    neg    pos  \
0  great look feel stepped back century novelty b...     4.0  0.000  0.301   
1  bad lot see fairly packed tourists even rainy ...     2.0  0.298  0.205   
2  houses look great nice walk around absolutely ...     3.0  0.000  0.496   
3  people housing area resident time business ren...     3.0  0.000  0.145   
4  bukchon hanok village situated middle modern p...     3.0  0.000  0.272   

     neu  compound     label  lstm_label  
0  0.699    0.8481  Positive         1.0  
1  0.497   -0.1280  Negative         0.0  
2  0.504    0.7845  Positive         1.0  
3  0.855    0.5994  Positive         1.0  
4  0.728    0.7964  Positive         1.0

In [98]:
df7['lstm_label']=np.where(df7['lstm_label']==1.0,1,0)
df7.head()

review  rating    neg    pos  \
0  great look feel stepped back century novelty b...     4.0  0.000  0.301   
1  bad lot see fairly packed tourists even rainy ...     2.0  0.298  0.205   
2  houses look great nice walk around absolutely ...     3.0  0.000  0.496   
3  people housing area resident time business ren...     3.0  0.000  0.145   
4  bukchon hanok village situated middle modern p...     3.0  0.000  0.272   

     neu  compound     label  lstm_label  rrating  
0  0.699    0.8481  Positive           1        1  
1  0.497   -0.1280  Negative           0        0  
2  0.504    0.7845  Positive           1        1  
3  0.855    0.5994  Positive           1        1  
4  0.728    0.7964  Positive           1        1

In [101]:
df7['nlstm_label']=np.where(df7.label=='Positive',1,0)
df7.head()


0.7877599058454295

In [139]:
np.mean(df7.lstm_label == df7.nlstm_label)

0.7877599058454295

In [99]:
np.mean(df7.lstm_label == df7.rrating)

0.8120831698705374

In [148]:
ldf4= pd.read_csv("C:\\Users\\USER\\Documents\\cheong_lemmatized.csv")
ldf4.head()

review  rating     label
0  came evening scenery quite beautiful wind blow...       5  Positive
1  people like strolling around stream especially...       5  Positive
2  long stream stretch km along stream find nicel...       5  Positive
3  first night everything decorated lantern buddh...       5  Positive
4  great illustration talent commitment korean pe...       4  Positive

In [149]:
ldf4['lstm_label']=np.zeros(len(ldf4))
ldf4.review=ldf4.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
ltwt8 = tokenizer.texts_to_sequences(ldf4['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
ltwt8 = pad_sequences(ltwt8, maxlen=max_length, dtype='int32', value=0)
print(ltwt8)

[[   0    0    0 ...  571 3093 1100]
 [   0    0    0 ...  212 5054 4837]
 [   0    0    0 ...   22  796    6]
 ...
 [   0    0    0 ... 4885   10  122]
 [   0    0    0 ...    5  129   25]
 [   0    0    0 ...   27   55  385]]


In [150]:
criteria = [ldf4['rating'].between(1, 2), ldf4['rating'].between(3, 5)]
values = [0, 1]

ldf4['rrating'] = np.select(criteria, values, 0)
ldf4.head()

review  rating     label  \
0  came evening scenery quite beautiful wind blow...       5  Positive   
1  people like strolling around stream especially...       5  Positive   
2  long stream stretch km along stream find nicel...       5  Positive   
3  first night everything decorated lantern buddh...       5  Positive   
4  great illustration talent commitment korean pe...       4  Positive   

   lstm_label  rrating  
0         0.0        1  
1         0.0        1  
2         0.0        1  
3         0.0        1  
4         0.0        1

In [151]:
sentiment= model.predict(ltwt8,batch_size=32,verbose = 2)
for i in range(len(ltwt8)):
    ldf4.iloc[i,3]=np.argmax(sentiment[i])


In [152]:
ldf4['lstm_label']=np.where(ldf4.lstm_label==1.0,1,0)
ldf4['nlstm_label']=np.where(ldf4.label=='Positive',1,0)
ldf4.head()

review  rating     label  \
0  came evening scenery quite beautiful wind blow...       5  Positive   
1  people like strolling around stream especially...       5  Positive   
2  long stream stretch km along stream find nicel...       5  Positive   
3  first night everything decorated lantern buddh...       5  Positive   
4  great illustration talent commitment korean pe...       4  Positive   

   lstm_label  rrating  nlstm_label  
0           1        1            1  
1           0        1            1  
2           1        1            1  
3           1        1            1  
4           1        1            1

In [153]:
np.mean(ldf4.lstm_label == ldf4.nlstm_label)

0.7527472527472527

In [155]:
np.mean(ldf4.lstm_label == ldf4.rrating)

0.7335164835164835

In [156]:
ldf4.to_csv('C:\\Users\\USER\\Documents\\relemmatized_cheong.csv',index=False) 

In [157]:
ldf5= pd.read_csv("C:\\Users\\USER\\Documents\\gung_lemmatized.csv")
ldf5.head()

ldf5['lstm_label']=np.zeros(len(ldf5))
ldf5.review=ldf5.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
ltwt5 = tokenizer.texts_to_sequences(ldf5['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
ltwt5 = pad_sequences(ltwt5, maxlen=max_length, dtype='int32', value=0)
print(ltwt5)

criteria = [ldf5['rating'].between(1, 2), ldf5['rating'].between(3, 5)]
values = [0, 1]

ldf5['rrating'] = np.select(criteria, values, 0)
ldf5.head()

sentiment= model.predict(ltwt5,batch_size=32,verbose = 2)
for i in range(len(ltwt5)):
    ldf5.iloc[i,3]=np.argmax(sentiment[i])

ldf5['lstm_label']=np.where(ldf5.lstm_label==1.0,1,0)
ldf5['nlstm_label']=np.where(ldf5.label=='Positive',1,0)
ldf5.head()



[[   0    0    0 ...   31   20  277]
 [   0    0    0 ...   18 1048   94]
 [   0    0    0 ...  427    2  582]
 ...
 [   0    0    0 ...  775    1 3941]
 [   0    0    0 ...  718  928  420]
 [   0    0    0 ...   82   31  277]]


review  rating     label  \
0  best way see place rent korean costume able ta...       5  Positive   
1  good palace overall may went first time lot pe...       4  Positive   
2  gate impressive ground well entrance fee inter...       4  Positive   
3  visited place around pm changing guard pm amaz...       5  Positive   
4  timing critical want see changing guard tour g...       5  Positive   

   lstm_label  rrating  nlstm_label  
0           1        1            1  
1           1        1            1  
2           1        1            1  
3           0        1            1  
4           0        1            1

In [159]:
np.mean(ldf5.lstm_label == ldf5.nlstm_label)
np.mean(ldf5.lstm_label == ldf5.rrating)
ldf5.to_csv('C:\\Users\\USER\\Documents\\relemmatized_gung.csv',index=False) 

0.5874509803921568

In [161]:
ldf6= pd.read_csv("C:\\Users\\USER\\Documents\\insadong_lemmatized.csv")
ldf6.head()

ldf6['lstm_label']=np.zeros(len(ldf6))
ldf6.review=ldf6.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
ltwt6 = tokenizer.texts_to_sequences(ldf6['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
ltwt6 = pad_sequences(ltwt6, maxlen=max_length, dtype='int32', value=0)
print(ltwt6)

criteria = [ldf6['rating'].between(1, 2), ldf6['rating'].between(3, 5)]
values = [0, 1]

ldf6['rrating'] = np.select(criteria, values, 0)
ldf6.head()

sentiment= model.predict(ltwt6,batch_size=32,verbose = 2)
for i in range(len(ltwt6)):
    ldf6.iloc[i,3]=np.argmax(sentiment[i])

ldf6['lstm_label']=np.where(ldf6.lstm_label==1.0,1,0)
ldf6['nlstm_label']=np.where(ldf6.label=='Positive',1,0)
ldf6.head()


[[   0    0    0 ...  397   63  357]
 [   0    0    0 ...  393  672   34]
 [   0    0    0 ...  494  420  121]
 ...
 [   0    0    0 ...   44   11  121]
 [   0    0    0 ...  183  247   11]
 [   0    0    0 ... 4272   11 1507]]


review  rating     label  \
0  well know place usually thing price varying tw...       5  Positive   
1  looking place buy local souvenir bunch local s...       4   Neutral   
2  shop many traditional korean art craft nice ar...       4  Positive   
3  main ntique street little tourist mall side st...       3  Positive   
4  bit atypical shopping area mix art gallery int...       4  Positive   

   lstm_label  rrating  nlstm_label  
0           1        1            1  
1           1        1            0  
2           1        1            1  
3           1        1            1  
4           1        1            1

In [163]:
np.mean(ldf6.lstm_label == ldf6.nlstm_label)
np.mean(ldf6.lstm_label == ldf6.rrating)
ldf6.to_csv('C:\\Users\\USER\\Documents\\relemmatized_insadong.csv',index=False) 

In [166]:
ldf7= pd.read_csv("C:\\Users\\USER\\Documents\\chon_lemmatized.csv")
ldf7.head()

ldf7['lstm_label']=np.zeros(len(ldf7))
ldf7.review=ldf7.review.astype(str)
#vectorizing the tweet by the pre-fitted tokenizer instance
ltwt7 = tokenizer.texts_to_sequences(ldf7['review'])
#padding the tweet to have exactly the same shape as `embedding_2` input
#pad_sequences(X_encoded, maxlen=max_length, padding='post'
ltwt7 = pad_sequences(ltwt7, maxlen=max_length, dtype='int32', value=0)
print(ltwt7)

criteria = [ldf7['rating'].between(1, 2), ldf7['rating'].between(3, 5)]
values = [0, 1]

ldf7['rrating'] = np.select(criteria, values, 0)
ldf7.head()

sentiment= model.predict(ltwt7,batch_size=32,verbose = 2)
for i in range(len(ltwt7)):
    ldf7.iloc[i,3]=np.argmax(sentiment[i])

ldf7['lstm_label']=np.where(ldf7.lstm_label==1.0,1,0)
ldf7['nlstm_label']=np.where(ldf7.label=='Positive',1,0)
ldf7.head()


[[   0    0    0 ...   20  238 1948]
 [   0    0    0 ...   26  568 1032]
 [   0    0    0 ...  352  229   59]
 ...
 [   0    0    0 ...   43  489   19]
 [   0    0    0 ...   26  199 4792]
 [   0    0    0 ...    0    0    0]]


review  rating     label  \
0  great look feel stepped back century novelty b...     4.0  Positive   
1  bad lot see fairly packed tourist even rainy d...     2.0  Negative   
2  house look great nice walk around absolutely p...     3.0  Positive   
3  people housing area resident time business ren...     3.0  Positive   
4  bukchon hanok village situated middle modern p...     3.0  Positive   

   lstm_label  rrating  nlstm_label  
0           1        1            1  
1           0        0            0  
2           1        1            1  
3           1        1            1  
4           1        1            1

In [169]:
ldf77=ldf7.drop(['rating', 'label'], axis=1)
ldf77.head(15)

review  lstm_label  rrating  \
0   great look feel stepped back century novelty b...           1        1   
1   bad lot see fairly packed tourist even rainy d...           0        0   
2   house look great nice walk around absolutely p...           1        1   
3   people housing area resident time business ren...           1        1   
4   bukchon hanok village situated middle modern p...           1        1   
5   really enjoyed walk around hilly neighborhood ...           1        1   
6   beautiful area hill small alley many still inh...           1        1   
7   like nice relaxing quite walk around outside l...           1        1   
8   nice romantic local korean village walk korean...           1        1   
9   lucky enough walk street le crowded one come a...           0        1   
10  like transported back time definitely must obs...           0        1   
11  place good visit great view peace co resident ...           1        1   
12  place great see old home however high tech doo...           1        1   
13  minute away gyeongbokgung palace changdeokung ...           0        1   
14  glad accompanied guide explained background re...           0        1   

    nlstm_label  
0             1  
1             0  
2             1  
3             1  
4             1  
5             1  
6             1  
7             1  
8             1  
9             1  
10            1  
11            1  
12            1  
13            0  
14            1

In [167]:
np.mean(ldf7.lstm_label == ldf7.nlstm_label)
np.mean(ldf7.lstm_label == ldf7.rrating)
ldf7.to_csv('C:\\Users\\USER\\Documents\\relemmatized_chon.csv',index=False) 

In [102]:
df7.to_csv('C:\\Users\\USER\\Documents\\re_bukchon.csv',index=False) 

In [123]:
df6.to_csv('C:\\Users\\USER\\Documents\\re_insadong.csv',index=False) 

In [137]:
df4.to_csv('C:\\Users\\USER\\Documents\\re_cheong.csv',index=False) 

In [138]:
df5.to_csv('C:\\Users\\USER\\Documents\\re_gung.csv',index=False)

In [ ]:
#p=1,n=0
#lstm_label: lstm 모델 돌려서 나온 결과 
#rrating: rate 3-5 는 positivie,1   , rate1-2 는 negative,0
#nlstm_label: vader 기준으로 나눈 p, n 